[package]
name = "crate_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
inarybay-runtime = { version = "*", path = "../runtime" }

[build-dependencies]
crate_tests_build = { version = "*", path = "../crate_tests_build" }
